### ISSUE TITLE
Is this project currently active? Confused how to get it working

### ISSUE THREAD

**Issue by yellownoggin** [chrisgriffith/autocomplete-angular-material#1]
Autocomplete not working for any angular-material specific tags or attribute.

Are we supposed to import / include those json files that you point to?

https://raw.githubusercontent.com/chrisgriffith/Angular-Material-Brackets-Extension/master/HtmlTags.json

thanks

**Comment by chrisgriffith** [comment]
You should install it via the Extension Manager in Brackets just like any other extension. The one issue that I can not resolve is if there is another code hinter installed, only one will work. Most likely that is the source of the issue.

**Comment by yellownoggin** [comment]
okay thanks for  the reply. I'm new to atom so I will work it more.
But 1 last question.  Can you give me example of another code hinter  that you have tried to use?
Thanks.
