### ISSUE TITLE
Autocomplete or snippet not working

### ISSUE THREAD

**Issue by reeveyew** [chrisgriffith/autocomplete-angular-material#2]
Installed the plugin in Atom. But the autocomplete or snippet is not working at all. I'm using Atom 1.4.0 Any idea?

**Comment by chrisgriffith** [comment]
My guess is there is a package conflict. Try disabling other third party packages, and seeing if it works.

**Comment by smkamranqadri** [comment]
me too didn't getting autocomplete

**Comment by chrisgriffith** [comment]
@smkamranqadri What packages do you have installed? Also what version of Atom?

**Comment by smkamranqadri** [comment]
it's working, actually i was looking for snippets for complete component where it's giving only auto-complete in element.
